
2023-02-24 17:24:35,363 - __main__ - ERROR - An error occurred
Traceback (most recent call last):
  File "C:\Users\eschu\OneDrive\Documents\EricsStuff\IQP\INaturalistTest\biodiversityWithLogging.py", line 291, in <module>
    createSheet(x)
  File "C:\Users\eschu\OneDrive\Documents\EricsStuff\IQP\INaturalistTest\biodiversityWithLogging.py", line 200, in createSheet
    worksheet = spreadsheet.add_worksheet(title=google_worksheet_name, rows=10, cols=10)
  File "C:\Users\eschu\anaconda3\lib\site-packages\gspread\spreadsheet.py", line 377, in add_worksheet
    data = self.batch_update(body)
  File "C:\Users\eschu\anaconda3\lib\site-packages\gspread\spreadsheet.py", line 131, in batch_update
    r = self.client.request(
  File "C:\Users\eschu\anaconda3\lib\site-packages\gspread\client.py", line 92, in request
    raise APIError(response)
gspread.exceptions.APIError: {'code': 400, 'message': 'Invalid requests[0].addSheet: A sheet with the name "Biodiversity Data 22" already exists. Please enter another name.', 'status': 'INVALID_ARGUMENT'}
2023-02-24 17:25:07,124 - __main__ - ERROR - An error occurred
Traceback (most recent call last):
  File "C:\Users\eschu\OneDrive\Documents\EricsStuff\IQP\INaturalistTest\temperatureWithLogging.py", line 111, in <module>
    createSheet()
  File "C:\Users\eschu\OneDrive\Documents\EricsStuff\IQP\INaturalistTest\temperatureWithLogging.py", line 52, in createSheet
    worksheet = spreadsheet.add_worksheet(title=google_worksheet_name, rows=10, cols=10)
  File "C:\Users\eschu\anaconda3\lib\site-packages\gspread\spreadsheet.py", line 377, in add_worksheet
    data = self.batch_update(body)
  File "C:\Users\eschu\anaconda3\lib\site-packages\gspread\spreadsheet.py", line 131, in batch_update
    r = self.client.request(
  File "C:\Users\eschu\anaconda3\lib\site-packages\gspread\client.py", line 92, in request
    raise APIError(response)
gspread.exceptions.APIError: {'code': 400, 'message': 'Invalid requests[0].addSheet: A sheet with the name "Biodiversity Data 22" already exists. Please enter another name.', 'status': 'INVALID_ARGUMENT'}
2023-02-25 16:39:39,071 - __main__ - ERROR - An error occurred
Traceback (most recent call last):
  File "<ipython-input-41-d2c18c17cf7a>", line 110, in <cell line: 16>
    createSheet()
  File "<ipython-input-41-d2c18c17cf7a>", line 51, in createSheet
    worksheet = spreadsheet.add_worksheet(title=google_worksheet_name, rows=10, cols=10)
  File "C:\Users\eschu\anaconda3\lib\site-packages\gspread\spreadsheet.py", line 377, in add_worksheet
    data = self.batch_update(body)
  File "C:\Users\eschu\anaconda3\lib\site-packages\gspread\spreadsheet.py", line 131, in batch_update
    r = self.client.request(
  File "C:\Users\eschu\anaconda3\lib\site-packages\gspread\client.py", line 92, in request
    raise APIError(response)
gspread.exceptions.APIError: {'code': 400, 'message': 'Invalid requests[0].addSheet: A sheet with the name "Biodiversity Data" already exists. Please enter another name.', 'status': 'INVALID_ARGUMENT'}
2023-02-25 16:39:39,071 - __main__ - ERROR - An error occurred
Traceback (most recent call last):
  File "<ipython-input-41-d2c18c17cf7a>", line 110, in <cell line: 16>
    createSheet()
  File "<ipython-input-41-d2c18c17cf7a>", line 51, in createSheet
    worksheet = spreadsheet.add_worksheet(title=google_worksheet_name, rows=10, cols=10)
  File "C:\Users\eschu\anaconda3\lib\site-packages\gspread\spreadsheet.py", line 377, in add_worksheet
    data = self.batch_update(body)
  File "C:\Users\eschu\anaconda3\lib\site-packages\gspread\spreadsheet.py", line 131, in batch_update
    r = self.client.request(
  File "C:\Users\eschu\anaconda3\lib\site-packages\gspread\client.py", line 92, in request
    raise APIError(response)
gspread.exceptions.APIError: {'code': 400, 'message': 'Invalid requests[0].addSheet: A sheet with the name "Biodiversity Data" already exists. Please enter another name.', 'status': 'INVALID_ARGUMENT'}
2023-02-25 16:40:13,812 - __main__ - ERROR - An error occurred
Traceback (most recent call last):
  File "C:\Users\eschu\OneDrive\Documents\EricsStuff\IQP\INaturalistTest\temperatureWithLogging.py", line 111, in <module>
    createSheet()
  File "C:\Users\eschu\OneDrive\Documents\EricsStuff\IQP\INaturalistTest\temperatureWithLogging.py", line 52, in createSheet
    worksheet = spreadsheet.add_worksheet(title=google_worksheet_name, rows=10, cols=10)
  File "C:\Users\eschu\anaconda3\lib\site-packages\gspread\spreadsheet.py", line 377, in add_worksheet
    data = self.batch_update(body)
  File "C:\Users\eschu\anaconda3\lib\site-packages\gspread\spreadsheet.py", line 131, in batch_update
    r = self.client.request(
  File "C:\Users\eschu\anaconda3\lib\site-packages\gspread\client.py", line 92, in request
    raise APIError(response)
gspread.exceptions.APIError: {'code': 400, 'message': 'Invalid requests[0].addSheet: A sheet with the name "Biodiversity Data" already exists. Please enter another name.', 'status': 'INVALID_ARGUMENT'}
2023-02-25 16:44:24,250 - __main__ - ERROR - An error occurred
Traceback (most recent call last):
  File "C:\Users\eschu\OneDrive\Documents\EricsStuff\IQP\INaturalistTest\biodiversityWithLogging.py", line 291, in <module>
    createSheet(x)
  File "C:\Users\eschu\OneDrive\Documents\EricsStuff\IQP\INaturalistTest\biodiversityWithLogging.py", line 200, in createSheet
    worksheet = spreadsheet.add_worksheet(title=google_worksheet_name, rows=10, cols=10)
  File "C:\Users\eschu\anaconda3\lib\site-packages\gspread\spreadsheet.py", line 377, in add_worksheet
    data = self.batch_update(body)
  File "C:\Users\eschu\anaconda3\lib\site-packages\gspread\spreadsheet.py", line 131, in batch_update
    r = self.client.request(
  File "C:\Users\eschu\anaconda3\lib\site-packages\gspread\client.py", line 92, in request
    raise APIError(response)
gspread.exceptions.APIError: {'code': 400, 'message': 'Invalid requests[0].addSheet: A sheet with the name "Biodiversity Data" already exists. Please enter another name.', 'status': 'INVALID_ARGUMENT'}
